export default {
  name: 'about',
  title: 'About / Hero',
  type: 'document',
  __experimental_actions: ['update', 'publish'],
  fields: [
    {
      name: 'headline',
      title: 'Headline',
      type: 'string',
      description: 'The big greeting text, e.g. "Aloha, I\'m Charlie."',
    },
    {
      name: 'bio',
      title: 'Bio',
      type: 'text',
      rows: 4,
      description: 'Short bio paragraph shown on the left side of the info panel.',
    },
    {
      name: 'currentRole',
      title: 'Current Role',
      type: 'string',
      description: 'e.g. "Senior Designer — DemandScience / Terminus"',
    },
    {
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g. "Based in the United States"',
    },
    {
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      description: 'Email address for the "Say hello" link.',
    },
    {
      name: 'currentCity',
      title: 'Current City',
      type: 'string',
      description: 'City name shown on the clock, e.g. "Indianapolis".',
    },
    {
      name: 'currentCountry',
      title: 'Current Country',
      type: 'string',
      description: 'Country code or name, e.g. "USA".',
    },
    {
      name: 'timezone',
      title: 'Timezone',
      type: 'string',
      description: 'IANA timezone string, e.g. "America/Indiana/Indianapolis".',
    },
    {
      name: 'latitude',
      title: 'Latitude',
      type: 'string',
      description: 'e.g. "39.7684° N"',
    },
    {
      name: 'longitude',
      title: 'Longitude',
      type: 'string',
      description: 'e.g. "86.1581° W"',
    },
    {
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
    },
    // ── Hero / Landing Page Fields (fully editable) ──
    {
      name: 'heroInitials',
      title: 'Hero Initials',
      type: 'string',
      description: 'Big bold initials, e.g. "CWC".',
    },
    {
      name: 'heroName',
      title: 'Hero Full Name',
      type: 'string',
      description: 'Full name displayed large.',
    },
    {
      name: 'heroRoles',
      title: 'Hero Roles',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Each item shows on its own line (e.g. Designer, Art Director).',
    },
    {
      name: 'heroBio',
      title: 'Hero Bio Line',
      type: 'string',
      description: 'Main line under the name (e.g. DESIGN, TECHNOLOGY...)',
    },
    {
      name: 'heroTagline',
      title: 'Hero Tagline',
      type: 'string',
      description: 'Second line below the bio.',
    },
    {
      name: 'heroAvailability',
      title: 'Hero Availability',
      type: 'string',
      description: 'e.g. AVAILABLE FOR WORK & TALKS',
    },
    {
      name: 'heroLocation',
      title: 'Hero Location Label',
      type: 'string',
      description: 'Top label, e.g. WORLDWIDE',
    },
  ],
}